### ISSUE TITLE
duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by nujcharee** [nhs-bnssg-analytics/PathSimR#3]
When i tried to do a dummy run from any input templates given I got the above error message.

**Comment by benmurch** [comment]
What templates are you using? Is this in the simulation tool section (where you upload calendar and network templates) or in the distribution fitter?


Ben Murch, Modelling and Analytics Manager
NHS Bristol, North Somerset & South Gloucestershire CCG

Tel: 0117 900 9593, email: ben.murch@nhs.net<mailto:ben.murch@nhs.net>, team email: bnssg.analytics@nhs.net<mailto:bnssg.analytics@nhs.net>

**Comment by nujcharee** [comment]
Hi 
Sorry I haven't given the enough info there

I used PathSimR_Shiny/network_templates/input_template_1 for network and PathSimR_Shiny/network_templates/cal_input_1 for calendar

Thank you very much.

**Comment by benmurch** [comment]
Can you just confirm it is the two attached templates you are using

And that you’re on this page

[cid:image001.png@01D6C401.4DCC89F0]

Ben Murch, Modelling and Analytics Manager
NHS Bristol, North Somerset & South Gloucestershire CCG

Tel: 0117 900 9593, email: ben.murch@nhs.net<mailto:ben.murch@nhs.net>, team email: bnssg.analytics@nhs.net<mailto:bnssg.analytics@nhs.net>
